#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
if [[ -f vendor/zlgcan_env.sh ]]; then
  # Generated by tools/install_zlg_sdk.sh
  source vendor/zlgcan_env.sh
fi
python3 tools/check_environment.py
exec ./run.sh
