from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Callable, Dict, Any, List
from app.models import DeviceConfig, CanFrame, FilterItem, SavedMessage, HardwareQueueFrame, LinFrame, LinSubscribe, LinPublish, LinSchedule

FrameCallback = Callable[[Dict[str, Any]], None]

class DriverError(RuntimeError):
    pass

class CanDriver(ABC):
    def __init__(self, on_frame: FrameCallback):
        self.on_frame = on_frame

    @abstractmethod
    def open(self, config: DeviceConfig) -> Dict[str, Any]: ...
    @abstractmethod
    def close(self) -> None: ...
    @abstractmethod
    def status(self) -> Dict[str, Any]: ...
    @abstractmethod
    def transmit(self, frame: CanFrame) -> int: ...
    @abstractmethod
    def clear_buffer(self, channel: int) -> None: ...
    @abstractmethod
    def reset_channel(self, channel: int) -> None: ...
    @abstractmethod
    def diagnostics(self, channel: int) -> Dict[str, Any]: ...
    @abstractmethod
    def configure_filters(self, channel: int, filters: List[FilterItem]) -> Dict[str, Any]: ...
    @abstractmethod
    def configure_hardware_periodic(self, msg: SavedMessage) -> Dict[str, Any]: ...
    @abstractmethod
    def clear_hardware_periodic(self, channel: int) -> Dict[str, Any]: ...
    @abstractmethod
    def queue_transmit(self, items: List[HardwareQueueFrame]) -> Dict[str, Any]: ...
    @abstractmethod
    def clear_tx_queue(self, channel: int) -> Dict[str, Any]: ...
    @abstractmethod
    def set_property(self, path: str, value: str) -> Dict[str, Any]: ...
    @abstractmethod
    def get_property(self, path: str) -> Dict[str, Any]: ...
    @abstractmethod
    def lin_transmit(self, frame: LinFrame) -> int: ...
    @abstractmethod
    def lin_subscribe(self, cfg: LinSubscribe) -> Dict[str, Any]: ...
    @abstractmethod
    def lin_publish(self, cfg: LinPublish) -> Dict[str, Any]: ...
    @abstractmethod
    def lin_schedule(self, cfg: LinSchedule) -> Dict[str, Any]: ...
